### ISSUE TITLE
First install: notangle is not available yet

### ISSUE THREAD

**Issue by romildo** [nrnrnr/noweb#1]
I want to package the latest version (from git) of `noweb` for my use with gentoo linux, but the package cannot be built unless `notangle` is already available. The problem is that `notangle` is not available in a first install. It will be available only after the package has been built.

Thus the "untangled" source files need to be made available in the git repository for such first installs. Please, add them.

**Comment by nrnrnr** [comment]
I have to consider how best to handle this problem.  Bootstrap files probably belong in a separate repository.  To be honest, if someone needs to bootstrap noweb, I think the best plan is not to use this git repo but to use one of the source distributions.   Unless you or someone else wants to volunteer to create a `noweb-bootstrap` repository, I will close this issue within a few days.

**Comment by romildo** [comment]
It is ok to bootstrap noweb using the released source distribution as long as it includes the generated source code and is *released more frequently*. The problem is that the latest release is too old and do not provide the latest features and fixes.

**Comment by nrnrnr** [comment]
Here's  a script you can use to bootstrap: http://www.cs.tufts.edu/~nr/nofake

**Comment by nrnrnr** [comment]
There is a more recent script at https://github.com/ctarbide/ctweb/blob/master/tools/nofake, with plenty of improvements.

Literate source at https://github.com/ctarbide/ctweb/blob/master/tools/nofake.nw
