### ISSUE TITLE
Generating file names containing '_' gives broken TeX

### ISSUE THREAD

**Issue by vonbrand** [nrnrnr/noweb#11]
When creating a tangled file with underscores, the resulting `*.tex` file bombs out:
(attached [bug.nw.txt](https://github.com/nrnrnr/noweb/files/6535774/bug.nw.txt) got `.txt` appended to appease github)

```
$ noweb bug.nw
$ pdflatex bug.tex
```

The LaTeX run errors out with:
```
! Missing $ inserted.
<inserted text> 
                $
l.13 ...}\subpageref{NWYfSjg-2rQ16a-1}}}\moddef{a_
                                                  fine_file_name.c~{\nwtagst...
```

A workaround is to edit the .tex file to replace `a_fine_file_name` with `a\_fine\_file\_name` throughout. Bletcherous...

**Comment by nrnrnr** [comment]
The `noweb` command is there for compatibility with `nuweb`.  It works as designed.  If you don't like the effects, don't use it. (I don't.)

**Comment by dbosk** [comment]
This bug is present when using `noweave` too. I've had to work around it when writing python modules (must use underscores).
```noweb
This is a typical module for Python.
<<my_module.py>>=
print("Hello, World!")
@
```
Running `notangle -Rmy_module.py my_module.nw` gives the correct Python file:
```python
print("Hello, World!")
```
Running `noweave my_module.nw` gives:
```LaTeX
\documentclass{article}\usepackage{noweb}\pagestyle{noweb}\noweboptions{}\begin{document}\nwfilename{test.nw}\nwbegindocs{0}This is a typical module for Python.% ===> this file was generated automatically by noweave --- better not edit it
\nwenddocs{}\nwbegincode{1}\moddef{my_module.py}\endmoddef\nwstartdeflinemarkup\nwenddeflinemarkup
print("Hello, World!")
\nwendcode{}\nwbegindocs{2}\nwdocspar
\nwenddocs{}\end{document}
```
But then compiling `pdflatex my_module.tex` breaks:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./my_module.tex
LaTeX2e <2020-10-01> patch level 1
L3 programming layer <2020-10-05> xparse <2020-03-03>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texmf/tex/plain/misc/noweb.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file my_module.aux.
! Missing $ inserted.
<inserted text> 
                $
l.2 \nwenddocs{}\nwbegincode{1}\moddef{my_
                                          module.py}\endmoddef\nwstartdeflin...

?
```

**Comment by dbosk** [comment]
But fixing it will likely break a neat feature. Consider the following:
```noweb
This is a typical module for Python.
<<my-module.py>>=
print("Hello, World!")
<<compute $\sum_i x_i$>>
@

To compute the sum, we do this:
<<compute $\sum_i x_i$>>=
sum(xs)
@
```
Which is very beautiful when compiled.

**Comment by dbosk** [comment]
I worked around it with the following construction in a `Makefile`:
```make
my-module.py: my_module.nw
    notangle -R$@ $^

my_module.py: my-module.py
    mv $^ $@
```

**Comment by nrnrnr** [comment]
It's not a bug.  By design, _chunk names are TeX source_.  They are not file names.

If you want to use chunk names as file names, then I encourage you to define a Noweb filter that can transmogrify a root-chunk name into suitable TeX.  That sort of thing is what filters are for.

**Comment by dbosk** [comment]
The filter suggestion is a neat idea. We'll see whenever I have the time to look into how to work with filters :-)
