### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by romildo** [nrnrnr/noweb#2]
If there is no big issue pending, please make a new release so that the package can be more easily installed (by Linux distributions, for instance).

**Comment by nrnrnr** [comment]
In June or July.

**Comment by romildo** [comment]
What about releasing 2.12? Can it be done?

**Comment by nrnrnr** [comment]
It never seems to be a high enough priority to rise to the top, does it?  

I suggest you poke me on December 12.  That's the day after I teach my last class of the semester, and I might be able to go for it.

**Comment by romildo** [comment]
> I suggest you poke me on December 12.

@nrnrnr A release now is welcome.

**Comment by nrnrnr** [comment]
If you are still interested, I have a release candidate on github now.

**Comment by nrnrnr** [comment]
The release is out.
