### ISSUE TITLE
Allow specification of chunk language

### ISSUE THREAD

**Issue by romildo** [nrnrnr/noweb#3]
There are situations where it is desirable to have a way of specifying the language of a code chunk in a literate document.

For instance, to enable an inner mode for editing the code chunk in editors like emacs. Or to pretty print the source code according to its language syntax.

Is it feasible to add such a feature in `noweb`? I would like to have it.

For instance, it could be something like

    <<definition of factorial>>=c
    int factorial(int n)
    {
       if (n <= 0)
          return 1;
       else
          return n * factorial(n - 1);
    }

**Comment by nrnrnr** [comment]
This feature has been requested many times.  My reply is always the same; chunk names should determine language.  You have your choice of two mechanisms:

- Formal markers at the end of a chunk name, as in 

    ````
    <<definition of factorial ((c))>>=
    int factorial (int n) ...
    ````

- Choose the language of a root chunk by matching a glob pattern, then propagate language from definition to use

I prefer the second of these methods, but both are viable.

**Comment by romildo** [comment]
Would the second method be something like

    \documentclass{article}
    \usepackage{noweb}

    \begin{document}

    \title{Calculating factorial}
    \maketitle

    In this mini article we will write a C program to calculate the
    factorial of natural number.

    The program is:
    <<factorial.c>>=
    #include <stdio.h>

    <<definition of fat>>

    <<main function>>
    @ 

    The factorial can be calculated by a recursive function:
    <<defintion of fact>>=
    int fact(const int n)
    {
      return n <= 0 ? 1 : n*fact(n-1);
    }
    @ 

    In the [[main]] function we just let the user inform the number, and
    then you show its factorial:
    <<main function>>=
    int main(void)
    {
       int x;
       printf("enter a natural number: ");
       scanf("%d", &x);
       int fx = fact(x);
       printf("%d! = %d\n", x, fx);
       return 0;
    }
    @ 

    In Haskell the factorial function could be defined as:
    <<factorial.haskell>>=
    fact :: Integer -> Integer
    fact n | n > 0 = n * fact (pred n)
    fact _         = 1
    @ 

    Interesting, don't you think?

    \end{document}

I suppose that here `<<factorial.c>>` and `<<factorial.haskell>>` are root chunks and `<<definition of fat>>` and `<<main function>>` are children chunks of `<<factorial.c>>`. So the language of `<<factorial.c>>` could be discovering by the extension `.c` and it would be propagated to its children.

If so, it seems to be impractical for use in discovering a major mode for inner chunks in emacs, as the full contents of the buffer would have to be analyzed to discover the proper mode for inner modes.

For pretty printing when typesetting the document it could work.

But if you mean another thing for the second method, please tell me.

The first method would be feasible for both use cases. Maybe a filter could be used to remove the language annotation in the typeset document.

**Comment by nrnrnr** [comment]
Yes, exactly.  And I intend that this second method be implemented in emacs polymode.  I expect the analysis to be quite practical, maybe even fast enough to do at every keystroke.  But certainly when polymode detects the transition from one indirect buffer to another.
