### ISSUE TITLE
noweb 2.12 build failure

### ISSUE THREAD

**Issue by chenrui333** [nrnrnr/noweb#31]
👋 trying to upgrade noweb to use the latest release, 2.12, but ran into some build failure, like this one

```
icont: cannot resolve reference to file 'xcode.u1'
```

relates to https://github.com/Homebrew/homebrew-core/pull/128379

**Comment by nrnrnr** [comment]
Your Icon installation evidently lacks the [Icon Program Library](https://www2.cs.arizona.edu/icon/library/). You could install the library, or you could comment out the request for `pdcached` in `src/icon/Makefile`.

I would accept a PR that improved the situation, either by improving documentation or by making the build conditional.

**Comment by chenrui333** [comment]
The pdcached removals work for me, filed [a new PR](https://github.com/Homebrew/homebrew-core/pull/133391) on upgrading to `2.12`
