### ISSUE TITLE
Spaces in chunks are not obeyed with TeX Live 2022

### ISSUE THREAD

**Issue by yurrriq** [nrnrnr/noweb#36]
Adding the following from https://tex.stackexchange.com/a/673393 to my preamble fixes it.

```tex
\makeatletter
\let\obeyedspace\@xobeysp
\makeatother
```

**Comment by nrnrnr** [comment]
I believe this issue was fixed already (#24).  What version of noweb are you using exactly?

**Comment by yurrriq** [comment]
Thanks. I was using [2.12](https://github.com/NixOS/nixpkgs/blob/c80b0906d5d0c27f59368ffc140376b8cccb2b95/pkgs/development/tools/literate-programming/noweb/default.nix#L5). I'll go ahead and updated nixpkgs while I'm at it.

**Comment by yurrriq** [comment]
Confirmed this works fine in 2.13. Thanks again.
