### ISSUE TITLE
Undefined chunks in src/tex/support.nw section Sub-page references

### ISSUE THREAD

**Issue by dbosk** [nrnrnr/noweb#38]
The following chunks are undefined:
- `<<ref value>>`,
- `<<page number>>`,
- `<<text>>`,
- `<<hyper category>>`, and
- `<<URL>>`.

Not sure if they were ever intended to be defined or if it was a shortcut to getting the <opt name> used in LaTeX docs. That worked until cross-refs arrived.
 
![image](https://github.com/nrnrnr/noweb/assets/237222/9f7855de-1bed-4386-be72-e7874424839a)

**Comment by nrnrnr** [comment]
They are not intended to be defined.  Just meant to be quoted using the existing mechanism.

There is unfortunately no simple way to turn off cross-reference tags within a limited scope.  If you wish to add one, I'll take a PR.
