### ISSUE TITLE
Why does -L break indentation?

### ISSUE THREAD

**Issue by dbosk** [nrnrnr/noweb#41]
I wanted to play around with tools such as `noerr.pl` to see how to handle line numbers in error messages. I noticed that adding the `-L` option breaks indentation. Consider `test.nw`:
```
<<test.py>>=
#!/usr/bin/python3

def main():
  <<main body>>

if __name__ == "__main__":
  main()
@

<<main body>>=
print("Hello, world!")
print(
@
```
A usual tangling (`notangle -t -Rtest.py test.nw`) gives this, as expected:
```python
#!/usr/bin/python3

def main():
  print("Hello, world!")
  print(

if __name__ == "__main__":
  main()
```
Adding the `-L` option breaks this (`notangle -t -L -Rtest.py test.nw`):
```python
#line 2 "test.nw"
#!/usr/bin/python3

def main():
  
#line 12 "test.nw"
print("Hello, world!")
print(

#line 7 "test.nw"
if __name__ == "__main__":
  main()
```
Note how the block inside `main()` is no longer indented.

I'll try to dig into this during the autumn semester, but we'll see when---it's a heavy teaching period. If you have time @nrnrnr, a hint would be appreciated.

**Comment by nrnrnr** [comment]
The Fine Manual says,

> When using the -Lformat option, notangle ensures that all text appears in the same column in input and output. 

That keeps column numbers accurate.

**Comment by dbosk** [comment]
My bad. It didn't occur to me that this would be the consequence of that phrasing.

I'm thinking about a designing my way around that so that I can use `-L` for languages like Python that depend on indentation. Before I start working on a PR, what do you think of having `%C` for column. If `%C` is present in the format string, `notangle` will not preserve columns but do indentation and the value of `%C` can be used to shift column values same as `%L` for lines.

With that design I think I can still keep indentation to keep Python happy, but still translate column numbers to match the column in the `.nw` source.

**Comment by nrnrnr** [comment]
What problem are you trying to solve?  Does Python use C-preprocessor directives? Formal comments?

**Comment by dbosk** [comment]
Sorry for vanishing, it was a hectic start of the autumn semester.

No, Python doesn't support preprocessor directives. But formal comments start with `#`, so my plan is to use comments and then filter through something like [noerr](https://github.com/svnk/noerr) to translate lines and columns.

Since Python is very strict about indentation, I must preserve indentation and, consequently, translate columns in addition to lines.

**Comment by nrnrnr** [comment]
If that is your goal, I would write a distinct noweb filter for your use case.  Basically just drop a formal comment at the beginning of every code chunk, then run `notangle` without the `-L` option.

It wouldn't shock me if there were already something like this kicking around the `contrib` tree, but it might be easier just to write one from scratch.

**Comment by dbosk** [comment]
Thanks, that's a good suggestion, I'll go for that approach!

Yeah, there are lots of things in the `contrib` tree. At times I've wanted to go through it. But the issue is always finding the time.
