### ISSUE TITLE
ctan marks noweb as obsolete

### ISSUE THREAD

**Issue by jonasstein** [nrnrnr/noweb#5]
Figure out why, and if it should be tagged "obsolete"
https://www.ctan.org/pkg/noweb

**Comment by nrnrnr** [comment]
I've hear from CTAN, and I have resolved this misunderstanding.  Once I provide a version that conforms to their current rules, they'll remove the marker.

**Comment by nrnrnr** [comment]
https://www.ctan.org/pkg/noweb is restored, and the package is no longer marked "obsolete."
