### ISSUE TITLE
Package for Gentoo Users

### ISSUE THREAD

**Issue by jonasstein** [nrnrnr/noweb#6]
The noweb package was removed from Gentoo, but we can add it again, if there are volunteers for testing and maintaining the package and if there are some users, who need this package.
You find the archived, old package on 
https://gitweb.gentoo.org/repo/gentoo.git/log/?qt=grep&q=noweb

**Comment by nrnrnr** [comment]
Version 2.12 is released.  Whether anyone wishes to reinstate the package at Gentoo, I leave to Gentoo.
