### ISSUE TITLE
Expose release tags to github

### ISSUE THREAD

**Issue by nrnrnr** [nrnrnr/noweb#7]
All releases are tagged, but github does not know about them.  Fix that.

**Comment by dbosk** [comment]
Sounds like it can be fixed by `git push --tags`.

**Comment by nrnrnr** [comment]
@dbosk nice!  Nothing in the documentation suggested that github would recognize my existing tags as "releases," but it does.

**Comment by dbosk** [comment]
Yes, it's a very nice feature indeed! I'm happy it solved the issue.
